* wepySCF fo BOMD and QM/MM WE simultions using weighted ensemble strategies

 
[[./info/logo/wepySCF_logo_v1_inkscape.svg]]

** This is a forked repo from DicksonLab's wepy software to run weighted ensemble simulation for QM and QMMM dynamics. 
Here you can find specific runners and architecture required for running QM or QM/MM simulations in weighted ensemble formalism.

As we are in the testing/prerelease phase, the installation and documentation is quite different from the parent wepy software.
Please follow the [[https://github.com/SamikBose/wepy_dev/blob/master/demos/PySCF/install_hpcc.md][ demo/PySCF]] to install in a hpc environment.
Also, use the Update installation tab to be on top of the updates.

If you have specific queiries regarding the qm or qmmm runners, distances, resamplers and boundary conditions: please contact Samik Bose at bosesami@msu.edu

Comes equipped with support for pyscf electronic structure package albeit a slightly modified md class can be found [[https://github.com/SamikBose/pyscf_dev][pyscf_dev]].
Utilizes parallelization using multiprocessing and the [[http://pubs.acs.org/doi/abs/10.1021/jp411479c][WExplore]] 
and [[https://pubmed.ncbi.nlm.nih.gov/31255090/][REVO]] (Resampling Ensembles by Variance Optimization) resampling
algorithms, and an HDF5 file format and library for storing and querying your WE datasets that can be used from the command line.

The deeper architecture of the parent ~wepy~ is maintained that allows freedom for fast development of new methods.

Full [[https://github.com/ADicksonLab/wepy/blob/master/info/introduction.org][introduction]].

** Installation
Please follow the [[https://github.com/SamikBose/wepy_dev/blob/master/demos/PySCF/install_hpcc.md][ demo/PySCF]] to install in a hpc environment.
Please follow the pyscf and gpu4pyscf installation instructions there carefully.

We recommend running this version of `wepy` in a conda environment using `python=3.10` or greater:


Cite the parent wepy software as:

#+begin_example
Samuel D. Lotz, Nazanin Donyapour, Alex Dickson, Tom Dixon, Nicole Roussey, & Rob Hall. (2020, August 4). ADicksonLab/wepy: 1.0.0 Major version release (Version v1.0.0). Zenodo. http://doi.org/10.5281/zenodo.3973431
#+end_example

[A second article on integration of QM softwares within wepy framework is coming up soon]



